import type { Project, ProjectTask, CreativeClub, WorkShowcase } from './types';

export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj_vogue_autumn',
    seekerId: 'usr_sarah_producer',
    title: 'Vogue India - Autumn Cinematic Campaign',
    rawTextBrief: 'High-fashion autumn visual editorial shooting across Mumbai heritage architecture and studio cyclorama. Requiring full-frame anamorphic camera package, high-contrast chiaroscuro lighting, and precise color grading.',
    parsedRequirements: {
      projectTitle: 'Vogue India - Autumn Cinematic Campaign',
      genre: 'Fashion / Commercial',
      tone: 'Cinematic High Contrast',
      targetBudgetTier: 'commercial',
      estimatedBudgetUsd: 1800000,
      shootDatesWindow: 'Nov 12 - Nov 15',
      shootDurationDays: 3,
      locationRequirement: 'Mumbai, Maharashtra',
      dynamicIntentSummary: '3-day commercial fashion campaign prioritizing high dynamic range and rich atmospheric tone.',
      rolesNeeded: [
        {
          roleTitle: 'Director of Photography',
          quantity: 1,
          mustHaveSkills: ['Anamorphic Cine Lenses', 'Sony FX6 / FX9 / Venice', 'Fashion Lighting'],
          niceToHaveSkills: ['Gimbal Operation'],
          estimatedDayRateUsd: 35000,
        },
        {
          roleTitle: 'Location Sound Recordist',
          quantity: 1,
          mustHaveSkills: ['Multi-track Dialogue', 'Schoeps / Sennheiser Mics'],
          niceToHaveSkills: ['Wireless Audio Feeds'],
          estimatedDayRateUsd: 25000,
        },
        {
          roleTitle: 'Lead Video Editor',
          quantity: 1,
          mustHaveSkills: ['DaVinci Resolve', 'Commercial Rhythms'],
          niceToHaveSkills: ['Color Grading'],
          estimatedDayRateUsd: 28000,
        },
      ],
      gearDependencies: [
        {
          category: 'Camera',
          itemOrSpecs: 'Full-Frame 4K/6K Cinema Camera with 10-bit 4:2:2 or RAW',
          mandatory: true,
        },
      ],
    },
    budgetUsd: 1800000,
    timeline: 'Nov 12 - Nov 15 (3 Production Days)',
    location: 'Mumbai, Maharashtra',
    genreTags: ['Fashion', 'Commercial', 'Anamorphic', 'Editorial'],
    collaboratorIds: ['usr_aman_dp', 'usr_elena_sound', 'usr_marcus_editor'],
    createdAt: '2026-09-06T10:00:00.000Z',
  },
  {
    id: 'proj_neon_monsoons',
    seekerId: 'usr_maya_director',
    title: 'Neon Monsoons (Narrative Short Film)',
    rawTextBrief: 'Atmospheric neo-noir thriller set during heavy monsoons in suburban Mumbai. Focused on moody night exteriors, practical neon reflections, and binaural audio design.',
    parsedRequirements: {
      projectTitle: 'Neon Monsoons (Narrative Short Film)',
      genre: 'Narrative / Neo-Noir',
      tone: 'Moody, Rain-soaked Night Realism',
      targetBudgetTier: 'indie',
      estimatedBudgetUsd: 850000,
      shootDatesWindow: 'Dec 1 - Dec 6',
      shootDurationDays: 5,
      locationRequirement: 'Mumbai, Maharashtra',
      dynamicIntentSummary: 'Intimate psychological thriller highlighting rain-soaked night-time realism.',
      rolesNeeded: [
        {
          roleTitle: 'Cinematographer',
          quantity: 1,
          mustHaveSkills: ['Low-Light Cinema Sensors', 'Waterproof Rigging', 'Practical Neon Lighting'],
          niceToHaveSkills: ['Car Mount Experience'],
          estimatedDayRateUsd: 30000,
        },
        {
          roleTitle: 'Sound Designer',
          quantity: 1,
          mustHaveSkills: ['Ambience Recording', 'Rain & Water Foley', 'Dolby Atmos Mix'],
          niceToHaveSkills: ['Modular Synth Textures'],
          estimatedDayRateUsd: 24000,
        },
        {
          roleTitle: 'Colorist',
          quantity: 1,
          mustHaveSkills: ['DaVinci Resolve', 'Film Emulation LUTs', 'ACES Workflow'],
          niceToHaveSkills: ['Grain & Halation Matching'],
          estimatedDayRateUsd: 22000,
        },
      ],
      gearDependencies: [
        {
          category: 'Audio',
          itemOrSpecs: 'Weather-resistant shotgun microphones with blimps & rain covers',
          mandatory: true,
        },
      ],
    },
    budgetUsd: 850000,
    timeline: 'Dec 1 - Dec 6 (5 Nights)',
    location: 'Mumbai, Maharashtra',
    genreTags: ['Narrative', 'Neo-Noir', 'Thriller', 'Atmospheric'],
    collaboratorIds: ['usr_aman_dp', 'usr_elena_sound', 'usr_marcus_editor'],
    createdAt: '2026-09-05T14:30:00.000Z',
  },
  {
    id: 'proj_kinetic_frame',
    seekerId: 'usr_jordan_uiux',
    title: 'Kinetic Frame - Interactive Media Exhibition',
    rawTextBrief: 'Interactive public installation exploring biometric movement and generative visuals using high-speed projection, camera motion tracking, and spatial sound.',
    parsedRequirements: {
      projectTitle: 'Kinetic Frame - Interactive Media Exhibition',
      genre: 'Interactive / Digital Arts',
      tone: 'Futuristic Generative Ambient',
      targetBudgetTier: 'indie',
      estimatedBudgetUsd: 650000,
      shootDatesWindow: 'Dec 15 - Dec 22',
      shootDurationDays: 7,
      locationRequirement: 'Bengaluru, Karnataka',
      dynamicIntentSummary: 'Large-scale experiential exhibition blending tech, motion graphics, and live music.',
      rolesNeeded: [
        {
          roleTitle: 'Motion Graphics Artist',
          quantity: 1,
          mustHaveSkills: ['After Effects', 'TouchDesigner / Unreal', 'Typography'],
          niceToHaveSkills: ['Projection Mapping'],
          estimatedDayRateUsd: 30000,
        },
        {
          roleTitle: 'Sound Designer',
          quantity: 1,
          mustHaveSkills: ['Spatial Audio', 'Generative Soundscapes'],
          niceToHaveSkills: ['Max MSP / Ableton'],
          estimatedDayRateUsd: 25000,
        },
      ],
      gearDependencies: [],
    },
    budgetUsd: 650000,
    timeline: 'Dec 15 - Dec 22',
    location: 'Bengaluru, Karnataka',
    genreTags: ['Interactive', 'Visual Arts', 'Motion Design', 'Exhibition'],
    collaboratorIds: ['usr_elena_sound', 'usr_marcus_editor'],
    createdAt: '2026-09-04T09:15:00.000Z',
  },
];

export const SEED_TASKS: ProjectTask[] = [
  {
    id: 'task_vogue_dp',
    projectId: 'proj_vogue_autumn',
    projectTitle: 'Vogue India - Autumn Cinematic Campaign',
    creatorId: 'usr_sarah_producer',
    title: 'Lead Cinematographer (Full-Frame Anamorphic)',
    description: 'Lead the camera and lighting team for 3 studio & outdoor location days in South Mumbai. Working alongside fashion stylists and international models.',
    category: 'cinematography',
    requiredRole: 'Director of Photography',
    requiredSkills: ['Anamorphic Lenses', 'Sony FX6 / FX9', 'High-Fashion Lighting'],
    dayRateInr: 35000,
    location: 'Mumbai, Maharashtra',
    durationDays: 3,
    status: 'open',
    createdAt: '2026-09-06T10:30:00.000Z',
  },
  {
    id: 'task_neon_sound',
    projectId: 'proj_neon_monsoons',
    projectTitle: 'Neon Monsoons (Narrative Short Film)',
    creatorId: 'usr_maya_director',
    title: 'Location Sound Recordist (Rain & Low-Noise Dialogue)',
    description: 'Capture clean multi-track dialogue in challenging night monsoon environments using weather-proof blimps and dual 32-bit float recorders.',
    category: 'sound',
    requiredRole: 'Location Sound Recordist',
    requiredSkills: ['Multi-track Dialogue', 'Sennheiser MKH 416', 'Weather Protection'],
    dayRateInr: 25000,
    location: 'Mumbai, Maharashtra',
    durationDays: 5,
    status: 'open',
    createdAt: '2026-09-05T15:00:00.000Z',
  },
  {
    id: 'task_neon_colorist',
    projectId: 'proj_neon_monsoons',
    projectTitle: 'Neon Monsoons (Narrative Short Film)',
    creatorId: 'usr_maya_director',
    title: 'Lead Colorist (DaVinci Resolve / ACES Night Look)',
    description: 'Craft a distinctive 35mm film-grain look, controlling neon skin-tones and deep shadows across rain sequences.',
    category: 'editing',
    requiredRole: 'Colorist',
    requiredSkills: ['DaVinci Resolve Studio', 'Film Stock Emulation', 'ACES Workflow'],
    dayRateInr: 22000,
    location: 'Mumbai, Maharashtra',
    durationDays: 4,
    status: 'open',
    createdAt: '2026-09-05T15:10:00.000Z',
  },
  {
    id: 'task_kinetic_motion',
    projectId: 'proj_kinetic_frame',
    projectTitle: 'Kinetic Frame - Interactive Media Exhibition',
    creatorId: 'usr_jordan_uiux',
    title: 'Kinetic Motion & Title Sequence Artist',
    description: 'Create high-resolution generative typographic loops and ambient projection visuals mapped to a 12-meter LED canvas.',
    category: 'design',
    requiredRole: 'Motion Graphics Artist',
    requiredSkills: ['After Effects', 'Typography Animation', 'Large-Format Rendering'],
    dayRateInr: 30000,
    location: 'Bengaluru, Karnataka',
    durationDays: 6,
    status: 'open',
    createdAt: '2026-09-04T11:00:00.000Z',
  },
];

export const SEED_CLUBS: CreativeClub[] = [
  {
    id: 'club_anamorphic_cinema',
    name: 'Anamorphic Cinema Society',
    tagline: 'Craft, lenses, and visual storytelling for narrative cinematographers.',
    description: 'A community of Directors of Photography, Gaffers, and Camera Operators sharing lens tests, lighting breakdowns, and collaborative kit share across India.',
    category: 'cinematography',
    tags: ['35mm Lenses', 'Lighting Rigs', 'Sensor Science', 'Camera Tech'],
    location: 'Mumbai, Maharashtra',
    memberCount: 148,
    avatarUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=300',
    coverImageUrl: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=1200',
    leadCreatorId: 'usr_aman_dp',
    meetingCadence: 'Bi-weekly lens sessions & screening breakdowns',
    activeProjectsCount: 4,
    createdAt: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'club_indie_producers',
    name: 'Independent Producers Guild',
    tagline: 'Connecting creative producers, line producers, and financing partners.',
    description: 'Facilitating film festival co-productions, international brand briefs, crew scheduling, and legal production contracts for independent cinema.',
    category: 'production',
    tags: ['Co-Production', 'Financing', 'Crew Packaging', 'Festival Circuits'],
    location: 'Mumbai & Pan-India',
    memberCount: 112,
    avatarUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=300',
    coverImageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200',
    leadCreatorId: 'usr_sarah_producer',
    meetingCadence: 'Monthly pitch roundtables & grant reviews',
    activeProjectsCount: 6,
    createdAt: '2026-08-10T10:00:00.000Z',
  },
  {
    id: 'club_sound_designers',
    name: 'Atmospheric Sound & Foley Guild',
    tagline: 'Field recording, dialogue restoration, and spatial audio exploration.',
    description: 'Audio artisans focused on pristine acoustic capture, custom contact mics, binaural soundscapes, and Dolby Atmos mastering.',
    category: 'sound',
    tags: ['Field Audio', 'Foley', 'Spatial Sound', 'Dolby Atmos'],
    location: 'Bengaluru, Karnataka',
    memberCount: 84,
    avatarUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=300',
    coverImageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200',
    leadCreatorId: 'usr_elena_sound',
    meetingCadence: 'Monthly soundwalks and DAW listening lounges',
    activeProjectsCount: 3,
    createdAt: '2026-08-18T14:00:00.000Z',
  },
  {
    id: 'club_directors_lab',
    name: 'Directors Lab India',
    tagline: 'Script workshops, table reads, and scene construction.',
    description: 'Narrative and commercial filmmakers dissecting blocked scenes, actor communications, and festival work-in-progress screenings.',
    category: 'directing',
    tags: ['Scene Blocking', 'Directing Actors', 'Narrative', 'Screenwriting'],
    location: 'Mumbai, Maharashtra',
    memberCount: 126,
    avatarUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300',
    coverImageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200',
    leadCreatorId: 'usr_maya_director',
    meetingCadence: 'Weekly table reads & script feedback labs',
    activeProjectsCount: 5,
    createdAt: '2026-08-20T16:00:00.000Z',
  },
];

export const SEED_WORKS: WorkShowcase[] = [
  {
    id: 'work_aman_reel',
    creatorId: 'usr_aman_dp',
    projectId: 'proj_vogue_autumn',
    projectTitle: 'Vogue India - Autumn Cinematic Campaign',
    title: '4K Cinematography & Lighting Showcase',
    description: 'Anamorphic compositions, high-contrast night exteriors, and handheld camera movement on Sony FX6 & ARRI Alexa.',
    mediaType: 'video',
    thumbnailUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=600&auto=format&fit=crop&q=80',
    linkUrl: 'https://youtube.com/watch?v=cinematography-aman',
    platform: 'youtube',
    category: 'cinematography',
    tags: ['Anamorphic', 'Low Light', 'Showreel', 'Arri / Sony'],
    rolesInvolved: ['Director of Photography', 'Gaffer', 'Colorist'],
    collaboratorIds: ['usr_sarah_producer', 'usr_marcus_editor'],
    appreciationCount: 342,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'work_vogue_campaign',
    creatorId: 'usr_sarah_producer',
    projectId: 'proj_vogue_autumn',
    projectTitle: 'Vogue India - Autumn Cinematic Campaign',
    title: 'Vogue Pacific Autumn Editorial 2025',
    description: 'High-end commercial and editorial fashion film captured on location with bespoke wardrobe styling and multi-camera setup.',
    mediaType: 'video',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
    linkUrl: 'https://youtube.com/watch?v=sample-vogue-ad',
    platform: 'youtube',
    category: 'production',
    tags: ['Fashion', 'Editorial', 'Commercial', 'Vogue'],
    rolesInvolved: ['Creative Producer', 'Cinematographer', 'Wardrobe Stylist', 'Editor'],
    collaboratorIds: ['usr_aman_dp', 'usr_marcus_editor', 'usr_elena_sound'],
    appreciationCount: 512,
    createdAt: '2026-08-25T11:00:00.000Z',
  },
  {
    id: 'work_elena_sound_reel',
    creatorId: 'usr_elena_sound',
    projectId: 'proj_neon_monsoons',
    projectTitle: 'Neon Monsoons (Narrative Short Film)',
    title: 'Atmospheric Soundscapes & Foley Master',
    description: 'Location audio recorded with Schoeps CMC641 and Sound Devices 833, featuring rain Foley and whisper-clear dialogue.',
    mediaType: 'audio',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80',
    linkUrl: 'https://vimeo.com/elenasoundlab',
    platform: 'vimeo',
    category: 'sound',
    tags: ['Dolby Atmos', 'Foley', 'Dialogue Restoration', 'Field Recording'],
    rolesInvolved: ['Location Sound Recordist', 'Sound Designer', 'Mixer'],
    collaboratorIds: ['usr_maya_director'],
    appreciationCount: 218,
    createdAt: '2026-08-28T14:30:00.000Z',
  },
  {
    id: 'work_maya_short',
    creatorId: 'usr_maya_director',
    projectId: 'proj_neon_monsoons',
    projectTitle: 'Neon Monsoons (Narrative Short Film)',
    title: 'Neon Monsoons (Directorial Teaser)',
    description: 'First-look teaser for narrative short film exploring memory and rain-soaked cityscapes.',
    mediaType: 'video',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    linkUrl: 'https://vimeo.com/sample-neon-monsoons',
    platform: 'vimeo',
    category: 'directing',
    tags: ['Narrative', 'Neo-Noir', 'Directing', 'Teaser'],
    rolesInvolved: ['Director', 'Director of Photography', 'Production Designer'],
    collaboratorIds: ['usr_aman_dp', 'usr_elena_sound'],
    appreciationCount: 289,
    createdAt: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'work_marcus_cut',
    creatorId: 'usr_marcus_editor',
    projectId: 'proj_vogue_autumn',
    projectTitle: 'Vogue India - Autumn Cinematic Campaign',
    title: 'Kinetic Rhythm Commercial Assembly',
    description: 'Dynamic pacing cut and DaVinci Resolve color timing for luxury lifestyle brand campaign.',
    mediaType: 'video',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80',
    linkUrl: 'https://vimeo.com/marcusvance-cuts',
    platform: 'vimeo',
    category: 'editing',
    tags: ['Commercial', 'Editing', 'DaVinci Resolve', 'Color Grading'],
    rolesInvolved: ['Lead Video Editor', 'Colorist'],
    collaboratorIds: ['usr_sarah_producer', 'usr_aman_dp'],
    appreciationCount: 265,
    createdAt: '2026-09-03T11:00:00.000Z',
  },
  {
    id: 'work_jordan_interactive',
    creatorId: 'usr_jordan_uiux',
    projectId: 'proj_kinetic_frame',
    projectTitle: 'Kinetic Frame - Interactive Media Exhibition',
    title: 'Kinetic Frame UI & Motion Design Study',
    description: 'Generative typography systems and real-time biometric visualizers designed for modern cultural spaces.',
    mediaType: 'image',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    linkUrl: 'https://behance.net/jordantaylor-systems',
    platform: 'behance',
    category: 'design',
    tags: ['Generative Design', 'Motion Graphics', 'UI/UX', 'Interactive'],
    rolesInvolved: ['Interactive Creative Director', 'Motion Designer'],
    appreciationCount: 194,
    createdAt: '2026-08-30T09:20:00.000Z',
  },
];
